# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 796ec4a501a7ca617416a3e86ddd0955c2c2d0ae81932325485689c981cf11f3dc193610d24e06c9fa34123edfa6b171647e4636e254428bce76c81e6b068e65

test:
  secret_key_base: 9eb5ac37c2b9a0c4b79f54a86dc6dac01b59e4a78092849b9722c85faad33763085c8243e13061e567173533689dcc3d646644483b5dad3ae4c90944aba12237

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
